[project]
name = "hospital-grupo2"
version = "0.1.0"
description = "Modelo híbrido DES+SD del colapso hospitalario — Ciudad UVG, sismo M6.8"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26",
    "pandas>=2.1",
    "openpyxl>=3.1",
    "matplotlib>=3.8",
    "ipykernel>=6.29",
    "jupyterlab>=4.0",
]

[tool.setuptools.packages.find]
where = ["src"]
